### ISSUE TITLE
Feature request: Make it usable for self hosted instances

### ISSUE THREAD

**Issue by saschafoerster** [calcom/wp-plugin#2]
Kindly asking you to make it possible to use any cal.com instance by adding just the full URL in the shortcode.

**Comment by PeerRich** [comment]
since its open source, you can easily just edit the php file and add your own

**Comment by saschafoerster** [comment]
Or if I would be able to, I would add an option field, that uses cal.com as default but also accepts other domains. But as I am not a programmer, I leave it here as an idea for future generations to come. ;)

**Comment by saschafoerster** [comment]
just works! Thank you very much @PeerRich!
